# Generated by Django 2.2 on 2020-06-11 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200611_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_categories', to='store.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_categories',
            field=models.ManyToManyField(blank=True, related_name='related_categories', to='store.Category'),
        ),
    ]
