# Generated by Django 2.2 on 2020-06-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_description',
            new_name='key_features',
        ),
    ]
